name: Actions workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
        - name: simple js action
          id: greet  #Only needed if referencing elsewhere
          uses: actions/hello-world-javascript-action@main
          with: 
            who-to-greet: Damion

        - name: log greeting time
          run: echo "${{ steps.greet.outputs.time }}"  # Steps is provided by github, the rest are specific to the action